davinci/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from hello_world import urls as hello_world_urls

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^hello_world/', include(hello_world_urls, namespace='hello_world')),
]

hello_world/urls.py
from django.conf.urls import url

from hello_world.views import hello_name, index


urlpatterns = [
    url(r'^hello$', hello_name, name='hello'),
    url(r'^$', index, name='index'),
]

hello_world/models.py
from __future__ import unicode_literals

from datetime import datetime

from django.db import models


RATING_VALUES = ((1, 1), (2, 2), (3, 3), (4, 4), (5, 5), )

DAYS_OF_WEEK = (
    ('sun', 'Sunday'),
    ('mon', 'Monday'),
    ('tues', 'Tuesday'),
    ('wed', 'Wednesday'),
    ('thurs', 'Thursday'),
    # fri
    # sat
)


class StuffToRate(models.Model):
    """
    This is a collection of things that cna be rated.
    It exists to service an an example of how to create a model that will
    be referenced from other models.
    """
    title = models.CharField(max_length=250)
    color = models.CharField(max_length=100, default='Green')
    description = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return 'StuffToRate - {} - {}'.format(self.title, self.color)

    def get_rating(self):
        if not self.rating_set.count():
            return 'No ratings for {}'.format(self.title)
        total = 0
        for rate in self.rating_set.all():
            total += rate.rating
        return total / self.rating_set.count()


class Rating(models.Model):
    stuff = models.ForeignKey(StuffToRate)
    rating = models.IntegerField(default=1, choices=RATING_VALUES)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return 'Rating -- {} -- {} -- {}'.format(self.stuff.title, self.rating,
                                                 self.stuff.color)


#####################


class Customer(models.Model):
    human_first_name = models.CharField(max_length=250)
    human_last_name = models.CharField(max_length=250)
    mileage = models.IntegerField(null=True, blank=True)

    def __unicode__(self):
        return '{} {}'.format(self.human_first_name, self.human_last_name)


class Pet(models.Model):
    name = models.CharField(max_length=200, default='Katie')
    breed = models.CharField(max_length=200)
    # customer = models.ForeignKey(Customer, None, related_name='thing', default=1, this_is_my_var='hello')
    customer = models.ForeignKey(Customer, default=1)

    def __unicode__(self):
        return 'Pet Name : {} belongs to : {} {}'.format(
            self.name, self.customer.human_first_name,
            self.customer.human_last_name)

    def __str__(self):
        return self.__unicode__()


class Service(models.Model):
    name = models.CharField(max_length=250)

    def __unicode__(self):
        return self.name


class Order(models.Model):
    # customer should be linked to Pet in production
    week_day = models.CharField(max_length=20, choices=DAYS_OF_WEEK)
    customer = models.ForeignKey(Customer)
    service = models.ManyToManyField(Service)


# class OrderToService(models.Model):
#     """
#     Example of how a ManyToMany field works at the database level.
#     """
#     order = models.ForeignKey(Order)
#     service = models.ForeignKey(Service)

hello_world/forms.py
from django import forms

from hello_world.models import Customer, Pet, Rating, Order, Service


class RatingForm(forms.ModelForm):
    class Meta:
        model = Rating
        fields = ['stuff', 'rating', ]


class PetSearchForm(forms.ModelForm):
    breed = forms.CharField(required=False)

    class Meta:
        model = Pet
        fields = ['name', 'breed', ]


class OrderForm(forms.ModelForm):
    service = forms.ModelMultipleChoiceField(
        queryset=Service.objects.all(),
        widget=forms.CheckboxSelectMultiple()
    )

    class Meta:
        model = Order
        fields = ['customer', 'service', 'week_day']


class NewOrderForm(forms.Form):
    customer = forms.ModelChoiceField(Customer.objects.all())
    mileage = forms.IntegerField(max_value=1000, min_value=0)

hello_world/views.py
from django.http import HttpResponse
from django.shortcuts import render

from hello_world.forms import NewOrderForm, PetSearchForm, RatingForm, OrderForm
from hello_world.models import Customer, Pet, Rating, StuffToRate


def index(request):
    # if request.method == 'POST':
    #     form = RatingForm(request.POST)
    #     if form.is_valid():
    #         form.save()
    # else:
    #     form = RatingForm()

    # import ipdb
    # ipdb.set_trace()

    if request.method == 'POST':

        form = OrderForm(request.POST)
        if form.is_valid():
            form.save()
    else:
        form = OrderForm()

    pets = []
    # if request.method == 'POST':
    #     form = PetSearchForm(request.POST)
    #     if form.is_valid():
    #         # cleaned_data is a dict populated by running is_valid
    #         # the dict values available are only those set from the
    #         # fields property
    #         search_dict = {}
    #         for field_name, field_value in form.cleaned_data.iteritems():
    #             if field_value:
    #                 search_dict[field_name] = field_value
    #         # pet_name = form.cleaned_data['name']
    #         # pets = Pet.objects.filter(name=pet_name)
    #         print 'Search dict:\n\t{}'.format(str(search_dict))
    #         pets = Pet.objects.filter(**search_dict)
    # else:
    #     form = PetSearchForm()
    objs = StuffToRate.objects.all()
    thing = StuffToRate.objects.get(id=1)
    context = {
        'objs': objs,
        'giraffe': thing,
        'form': form,
        'pets': pets,
    }
    return render(request, 'base.html', context)


def hello_name(request):
    # display = 'Hello Alvin this is hello_name function inside hello_world.views'
    # return HttpResponse(display)

    if request.method == 'POST':

        customer_id = request.POST['customer']
        cust = Customer.objects.get(id=customer_id)
        data = {
            'customer': cust,
            'mileage': cust.mileage * 2,
        }
        # print '------------------ \n {} \n --------------------'.format(data)
        form = NewOrderForm(initial=data)
        if form.is_valid():
            pass
    else:
        form = NewOrderForm()

    context = {
        'form': form,
    }

    return render(request, 'base.html', context)

hello_world/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>DaVinci Django</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <style>
        td, th {
            padding: 10px;
            border: 1px solid black;
        }
    </style>
</head>
<body>
<ul class="nav nav-tabs">
  <li role="presentation" class="active"><a href="#">Home</a></li>
  <li role="presentation"><a href="#">Profile</a></li>
  <li role="presentation"><a href="#">Messages</a></li>
</ul>

<h1>My Search Form</h1>
{#<form method="post" action="{% url 'hello_world:hello' %}">#}
<form method="post">
{#<form method="post" action="/hello_world/hello">#}
    {{ form }}
    <input type="submit" value="Search">
    {% csrf_token %}
</form>

{% comment %}

<h1>Pets</h1>
<table>
    <tr>
    {% for obj in pets %}
        <tr>
            <td>{{ obj.id }}</td>
            <td>{{ obj.name }}</td>
        </tr>
    {% endfor %}
    </tr>
</table>

{% comment %}
<h1>This is my heading</h1>
<table>
    <tr>
        <td>{{ giraffe.title }}</td>
        <td>{{ giraffe.color }}</td>
        <td></td>
        <td></td>
    </tr>

    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>

    {% for obj in objs %}
        <tr>
            <td>{{ obj.id }}</td>
            <td>{{ obj.title }}</td>
            <td>{{ obj.color }}</td>
            <td>{{ obj.get_rating }}</td>
        </tr>
    {% endfor %}
    <tr>
        <td>Column 1</td>
        <td></td>
        <td>Column 3</td>
        <td></td>
    </tr>
</table>

{% endcomment %}

</body>
</html>

hello_world/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
      <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
      <input type="hidden" name="next" value="/hello_world">
  </form>
</body>
</html>

hello_world/templates/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Logout</title>
</head>
<body>
  <h2>Logged out</h2>
  <p>By visiting the logout URL you were logged out.</p>
  <p><a href="{% url 'login' %}">Log in</a> again.</p>
</body>
</html>

hello_world/templates/objs.html
{% extends 'base.html' %}

{% block content %}
    {{ block.super }}

    <!-- I'm objs content -->

    <h1>My Form</h1>
    <form method="post">
        {{ form }}
        <input type="submit" value="Save">
        {% csrf_token %}
    </form>
{% endblock %}

hello_world/templates/objs_list.html
{% extends 'objs.html' %}

{% block content %}
    {{ block.super }}


    <!-- I'm objs_list content -->

    <h1>This is my heading</h1>


    <table>
        <tr>
            <td>{{ giraffe.title }}</td>
            <td>{{ giraffe.color }}</td>
            <td></td>
            <td></td>
        </tr>

        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>

        {% for obj in objs %}
            <tr>
                <td>{{ obj.id }}</td>
                <td>{{ obj.title }}</td>
                <td>{{ obj.color }}</td>
                <td>{{ obj.get_rating }}</td>
            </tr>
        {% endfor %}
        <tr>
            <td>Column 1</td>
            <td></td>
            <td>Column 3</td>
            <td></td>
        </tr>
    </table>
{% endblock %}